# Generated by Django 5.0.7 on 2024-07-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='Fecha Publicación',
        ),
    ]
