# Generated by Django 5.0.7 on 2024-07-25 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_public',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 43, 57, 358028)),
        ),
    ]
