# Generated by Django 5.0.7 on 2024-07-25 02:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_post_fecha_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_public',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 49, 13, 428768)),
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.post')),
            ],
        ),
    ]
